# Generated by Django 3.2.6 on 2021-09-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilede_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='url',
        ),
        migrations.AddField(
            model_name='search',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
    ]
