# Generated by Django 3.2.6 on 2021-09-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilede_parser', '0002_auto_20210902_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='url',
        ),
        migrations.AddField(
            model_name='ad',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
    ]
