version: "3.8"

services:
  web:
    build: .
    working_dir: /code
    command: ./web-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
