version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    restart: unless-stopped
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    working_dir: /code
    command: ./web-entrypoint.sh
    volumes:
      - .:/code
      - staticfiles:/code/staticfiles
    env_file:
      - .env
    restart: unless-stopped

volumes:
  staticfiles:
