version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/app/staticfiles/
      - ./nginx_conf:/etc/nginx/conf.d/
    restart: unless-stopped
    depends_on:
      - web

  web:
    build: .
    command: ./web-entrypoint.sh
    volumes:
      - .:/code
      - staticfiles:/code/staticfiles/
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  worker:
    build: .
    command: ./worker-entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - broker

  beat:
    build: .
    command: ./beat-entrypoint.sh
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - broker

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  broker:
    image: redis

volumes:
  db_data:
  staticfiles:
