version: "3.8"

services:
  nginx:
    image: "${NGINX_IMAGE}"
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    restart: unless-stopped
    depends_on:
      - web

  web:
    image: "${WEB_IMAGE}"
    command: ./web-entrypoint.sh
    volumes:
      - staticfiles:/code/staticfiles
    env_file:
      - .env
    restart: unless-stopped

  standalone-chrome:
    image: selenium/standalone-chrome
    shm_size: "2g"

volumes:
  staticfiles:
