version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    restart: unless-stopped
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./web-entrypoint.sh
    volumes:
      - .:/code
      - staticfiles:/code/staticfiles
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  standalone-chrome:
    image: selenium/standalone-chrome
    shm_size: "2g"

volumes:
  db_data:
  staticfiles:
