# Generated by Django 3.2.5 on 2021-08-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='telegram id'),
        ),
    ]
